### ISSUE TITLE
Browser tab freezes every few seconds

### ISSUE THREAD

**Issue by vutondesign** [vutondesign/wait#8]
Reported from a user (@bwbw223) on scratch:

> It freezes my browser tab every few seconds. 😕 
Firefox 57 (and nightly) on MacOS.

**Comment by redmangospros** [comment]
MAybe too much code?

**Comment by vutondesign** [comment]
> Maybe too much code?

There actually isn't much code behind this, I'm waiting for a repro and more info from @bwbw223.

**Comment by vutondesign** [comment]
I can seem to repro this at all on firefox 57 and nightly, Please let me know if anyone has this problem.
